# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Darin Lei
tagline:          'HBSc Candidate at the University of Toronto'
description:      'A curious researcher.'
url:              https://darinlei.github.io
baseurl:          ""

author:
  name:           'Darin Lei'
  url:            https://www.linkedin.com/in/darin-lei/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/apollochapter/darinlei

plugins:
  - jekyll-paginate
